### ISSUE TITLE
Debian 11 not working

### ISSUE THREAD

**Issue by matteu31400** [vmware-samples/packer-examples-for-vsphere#336]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

22.09 (latest)

### VMware vSphere

7.0.3

### HashiCorp Packer

1.8.4

### HashiCorp Packer Plugin for VMware vSphere

1.1.0

### Guest Operating System

Debian 11

### Environment Details

Debian 11 with vcenter last version

### Description

Deployment for Debian 11 is not working

### Expected Behavior

enter ./build.sh -> choice 2 -> y and then the template is created automatically

### Actual Behavior

The VM is blocked on network setup during Debian wizzard installation

### Steps to Reproduce

Use default configuration file

### Additional Context

I think there are several issue on this part :

  boot_command = [
    "<wait3s>c<wait3s>",
    "linux /install.amd/vmlinuz",
    " auto-install/enable=true",
    " debconf/priority=critical",
    " ${local.data_source_command}",
    " noprompt --<enter>",
    "initrd /install.amd/initrd.gz<enter>",
    "boot<enter>",
    "<wait30s>",
    "<enter><wait>",
    "<enter><wait>",
    "<leftAltOn><f2><leftAltOff>",
    "<enter><wait>",
    "mount /dev/sr1 /media<enter>",
    "<leftAltOn><f1><leftAltOff>",
    "<down><down><down><down><enter>"
  ]

First : There is no /dev/sr1 but only /dev/sr0
Second : Last line is not ok. It should be only enter
Then I don't know what should be selected for network configuration to work : automatically ? configure later ?
Finally : after some times if I manually push the settings, I have an error durring application installation.

**Comment by tenthirtyam** [comment]
I’ll look at the issue once I return from sabbatical; however, I ran the same last week without any issues.

Please note the OS and version on which Packer is running - Ubuntu, Photon, or MacOS.

**Comment by tenthirtyam** [comment]
Also note that sr1 is only used if the data source is changed to disk vs http.

**Comment by tenthirtyam** [comment]
Unable to reproduce with Release v22.09 using Ubuntu 22.04 LTS for the Packer host.

<details open>
<summary>HTTP-based Source</summary>


```console
CONFIRM: Build a Debian 11 Template for VMware vSphere?

Continue? (y/n)
y
Building a Debian 11 Template for VMware vSphere...
Initializing HashiCorp Packer and required plugins...
Starting the build....
vsphere-iso.linux-debian: output will be in this color.

==> vsphere-iso.linux-debian: the vm/template Templates/linux-debian-11-v22.11 already exists, but deleting it due to -force flag
==> vsphere-iso.linux-debian: Creating VM...
==> vsphere-iso.linux-debian: Customizing hardware...
==> vsphere-iso.linux-debian: Adding SATA controller...
==> vsphere-iso.linux-debian: Mounting ISO images...
==> vsphere-iso.linux-debian: Adding configuration parameters...
==> vsphere-iso.linux-debian: Starting HTTP server on port 8063
==> vsphere-iso.linux-debian: Set boot order...
==> vsphere-iso.linux-debian: Power on VM...
==> vsphere-iso.linux-debian: Waiting 5s for boot...
==> vsphere-iso.linux-debian: HTTP server is working at http://172.16.14.200:8063/
==> vsphere-iso.linux-debian: Typing boot command...
==> vsphere-iso.linux-debian: Waiting for IP...
==> vsphere-iso.linux-debian: IP address: 172.16.14.198
==> vsphere-iso.linux-debian: Using SSH communicator to connect: 172.16.14.198
==> vsphere-iso.linux-debian: Waiting for SSH to become available...
==> vsphere-iso.linux-debian: Connected to SSH!
==> vsphere-iso.linux-debian: Provisioning with Ansible...
    vsphere-iso.linux-debian: Setting up proxy adapter for Ansible....
==> vsphere-iso.linux-debian: Executing Ansible: <sensitive>-playbook -e packer_build_name="linux-debian" -e packer_builder_type=vsphere-iso -e packer_http_addr=172.16.14.200:8063 --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars display_skipped_hosts=false --extra-vars BUILD_USERNAME=<sensitive> --extra-vars BUILD_SECRET=***** --extra-vars ANSIBLE_USERNAME=<sensitive> --extra-vars ANSIBLE_SECRET=***** -e <sensitive>_ssh_private_key_file=/tmp/<sensitive>-key3214948029 -i /tmp/packer-provisioner-<sensitive>2848424060 /home/packer/packer-vsphere/<sensitive>/main.yml
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY [all] *********************************************************************
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [Gathering Facts] *********************************************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/base/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Updating the guest operating system.] *****************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Installing additional packages.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/users/tasks/linux.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys for the default local user.] **************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the default local user to passwordless sudoers.] **********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Creating a local user for Ansible.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys to the local user for Ansible.] ***********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the local user for Ansible to passwordless sudoers.] ******
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/configure/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Configure SSH for Public Key Authentication.] ****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting hostname to localhost.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Restarting the SSH daemon.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Disabling and clean tmp.] ************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting SSH keys to regenerate on reboot, if neccessary.] ****
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting guest operating system information.] *****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/clean/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning all audit logs.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning persistent udev rules.] *********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the /tmp directories] ***********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the SSH host keys.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the machine-id.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the shell history.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY RECAP *********************************************************************
    vsphere-iso.linux-debian: default                    : ok=24   changed=18   unreachable=0    failed=0    skipped=16   rescued=0    ignored=0
    vsphere-iso.linux-debian:
==> vsphere-iso.linux-debian: Executing shutdown command...
==> vsphere-iso.linux-debian: Deleting Floppy drives...
==> vsphere-iso.linux-debian: Eject CD-ROM drives...
==> vsphere-iso.linux-debian: Deleting CD-ROM drives...
==> vsphere-iso.linux-debian: Clear boot order...
==> vsphere-iso.linux-debian: Importing VM OVF template linux-debian-11-v22.11 to Content Library 'm01-lib01' as the item 'linux-debian-11-v22.11' with the description 'Version: v22.11
==> vsphere-iso.linux-debian: Built on: 2022-11-08 03:01 UTC
==> vsphere-iso.linux-debian: Built by: HashiCorp Packer 1.8.4'...
==> vsphere-iso.linux-debian: Destroying VM...
==> vsphere-iso.linux-debian: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-debian' finished after 7 minutes 27 seconds.

==> Wait completed after 7 minutes 27 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
Done.
Press Enter to continue.
```
</details>

<details open>
<summary>Disk-based Source</summary>


```console
CONFIRM: Build a Debian 11 Template for VMware vSphere?

Continue? (y/n)
y
Building a Debian 11 Template for VMware vSphere...
Initializing HashiCorp Packer and required plugins...
Starting the build....
vsphere-iso.linux-debian: output will be in this color.

==> vsphere-iso.linux-debian: Creating CD disk...
    vsphere-iso.linux-debian: xorriso 1.5.4 : RockRidge filesystem manipulator, libburnia project.
    vsphere-iso.linux-debian: Drive current: -outdev 'stdio:/tmp/packer1447612905.iso'
    vsphere-iso.linux-debian: Media current: stdio file, overwriteable
    vsphere-iso.linux-debian: Media status : is blank
    vsphere-iso.linux-debian: Media summary: 0 sessions, 0 data blocks, 0 data, 35.9g free
    vsphere-iso.linux-debian: xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
    vsphere-iso.linux-debian: Added to ISO image: directory '/'='/tmp/packer_to_cdrom769529112'
    vsphere-iso.linux-debian: xorriso : UPDATE :       1 files added in 1 seconds
    vsphere-iso.linux-debian: xorriso : UPDATE :       1 files added in 1 seconds
    vsphere-iso.linux-debian: ISO image produced: 188 sectors
    vsphere-iso.linux-debian: Written to medium : 188 sectors at LBA 0
    vsphere-iso.linux-debian: Writing to 'stdio:/tmp/packer1447612905.iso' completed successfully.
    vsphere-iso.linux-debian: Done copying paths from CD_dirs
==> vsphere-iso.linux-debian: Uploading packer1447612905.iso to packer_cache/packer1447612905.iso
==> vsphere-iso.linux-debian: Creating VM...
==> vsphere-iso.linux-debian: Customizing hardware...
==> vsphere-iso.linux-debian: Adding SATA controller...
==> vsphere-iso.linux-debian: Mounting ISO images...
==> vsphere-iso.linux-debian: Adding configuration parameters...
==> vsphere-iso.linux-debian: Set boot order...
==> vsphere-iso.linux-debian: Power on VM...
==> vsphere-iso.linux-debian: Waiting 5s for boot...
==> vsphere-iso.linux-debian: Typing boot command...
==> vsphere-iso.linux-debian: Waiting for IP...
==> vsphere-iso.linux-debian: IP address: 172.16.14.162
==> vsphere-iso.linux-debian: Using SSH communicator to connect: 172.16.14.162
==> vsphere-iso.linux-debian: Waiting for SSH to become available...
==> vsphere-iso.linux-debian: Connected to SSH!
==> vsphere-iso.linux-debian: Provisioning with Ansible...
    vsphere-iso.linux-debian: Setting up proxy adapter for Ansible....
==> vsphere-iso.linux-debian: Executing Ansible: <sensitive>-playbook -e packer_build_name="linux-debian" -e packer_builder_type=vsphere-iso -e packer_http_addr=172.16.11.253:0 --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars display_skipped_hosts=false --extra-vars BUILD_USERNAME=<sensitive> --extra-vars BUILD_SECRET=***** --extra-vars ANSIBLE_USERNAME=<sensitive> --extra-vars ANSIBLE_SECRET=***** -e <sensitive>_ssh_private_key_file=/tmp/<sensitive>-key511489969 -i /tmp/packer-provisioner-<sensitive>1724375913 /home/packer/packer-vsphere/<sensitive>/main.yml
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY [all] *********************************************************************
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [Gathering Facts] *********************************************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/base/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Updating the guest operating system.] *****************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Installing additional packages.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/users/tasks/linux.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys for the default local user.] **************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the default local user to passwordless sudoers.] **********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Creating a local user for Ansible.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys to the local user for Ansible.] ***********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the local user for Ansible to passwordless sudoers.] ******
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/configure/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Configure SSH for Public Key Authentication.] ****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting hostname to localhost.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Restarting the SSH daemon.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Disabling and clean tmp.] ************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting SSH keys to regenerate on reboot, if neccessary.] ****
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting guest operating system information.] *****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/clean/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning all audit logs.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning persistent udev rules.] *********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the /tmp directories] ***********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the SSH host keys.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the machine-id.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the shell history.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY RECAP *********************************************************************
    vsphere-iso.linux-debian: default                    : ok=24   changed=18   unreachable=0    failed=0    skipped=16   rescued=0    ignored=0
    vsphere-iso.linux-debian:
==> vsphere-iso.linux-debian: Executing shutdown command...
==> vsphere-iso.linux-debian: Deleting Floppy drives...
==> vsphere-iso.linux-debian: Eject CD-ROM drives...
==> vsphere-iso.linux-debian: Deleting CD-ROM drives...
==> vsphere-iso.linux-debian: Clear boot order...
==> vsphere-iso.linux-debian: Importing VM OVF template linux-debian-11-v22.11 to Content Library 'm01-lib01' as the item 'linux-debian-11-v22.11' with the description 'Version: v22.11
==> vsphere-iso.linux-debian: Built on: 2022-11-08 03:11 UTC
==> vsphere-iso.linux-debian: Built by: HashiCorp Packer 1.8.4'...
==> vsphere-iso.linux-debian: Destroying VM...
==> vsphere-iso.linux-debian: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-debian' finished after 7 minutes 24 seconds.

==> Wait completed after 7 minutes 24 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
Done.
Press Enter to continue.
```
</details>

**Comment by tenthirtyam** [comment]
Also unable to reproduce with latest from `main` using Ubuntu 22.04 LTS for the Packer host.

<details open>
<summary>HTTP-based Source</summary>


```console
CONFIRM: Build a Debian 11 Template for VMware vSphere?

Continue? (y/n)
y
Building a Debian 11 Template for VMware vSphere...
Initializing HashiCorp Packer and required plugins...
Starting the build....
vsphere-iso.linux-debian: output will be in this color.

==> vsphere-iso.linux-debian: Creating VM...
==> vsphere-iso.linux-debian: Customizing hardware...
==> vsphere-iso.linux-debian: Adding SATA controller...
==> vsphere-iso.linux-debian: Mounting ISO images...
==> vsphere-iso.linux-debian: Adding configuration parameters...
==> vsphere-iso.linux-debian: Starting HTTP server on port 8097
==> vsphere-iso.linux-debian: Set boot order...
==> vsphere-iso.linux-debian: Power on VM...
==> vsphere-iso.linux-debian: Waiting 5s for boot...
==> vsphere-iso.linux-debian: HTTP server is working at http://172.16.14.200:8097/
==> vsphere-iso.linux-debian: Typing boot command...
==> vsphere-iso.linux-debian: Waiting for IP...
==> vsphere-iso.linux-debian: IP address: 172.16.14.185
==> vsphere-iso.linux-debian: Using SSH communicator to connect: 172.16.14.185
==> vsphere-iso.linux-debian: Waiting for SSH to become available...
==> vsphere-iso.linux-debian: Connected to SSH!
==> vsphere-iso.linux-debian: Provisioning with Ansible...
    vsphere-iso.linux-debian: Setting up proxy adapter for Ansible....
==> vsphere-iso.linux-debian: Executing Ansible: <sensitive>-playbook -e packer_build_name="linux-debian" -e packer_builder_type=vsphere-iso -e packer_http_addr=172.16.14.200:8097 --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars display_skipped_hosts=false --extra-vars BUILD_USERNAME=<sensitive> --extra-vars BUILD_SECRET=***** --extra-vars ANSIBLE_USERNAME=<sensitive> --extra-vars ANSIBLE_SECRET=***** -e <sensitive>_ssh_private_key_file=/tmp/<sensitive>-key2017251931 -i /tmp/packer-provisioner-<sensitive>3506479477 /home/packer/packer-vsphere/<sensitive>/main.yml
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY [all] *********************************************************************
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [Gathering Facts] *********************************************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/base/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Updating the guest operating system.] *****************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Installing additional packages.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/users/tasks/linux.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys for the default local user.] **************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the default local user to passwordless sudoers.] **********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Creating a local user for Ansible.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys to the local user for Ansible.] ***********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the local user for Ansible to passwordless sudoers.] ******
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/configure/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Configure SSH for Public Key Authentication.] ****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting hostname to localhost.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Restarting the SSH daemon.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Disabling and clean tmp.] ************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting SSH keys to regenerate on reboot, if neccessary.] ****
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting guest operating system information.] *****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/clean/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning all audit logs.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning persistent udev rules.] *********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the /tmp directories] ***********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the SSH host keys.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the machine-id.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the shell history.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY RECAP *********************************************************************
    vsphere-iso.linux-debian: default                    : ok=24   changed=18   unreachable=0    failed=0    skipped=16   rescued=0    ignored=0
    vsphere-iso.linux-debian:
==> vsphere-iso.linux-debian: Executing shutdown command...
==> vsphere-iso.linux-debian: Deleting Floppy drives...
==> vsphere-iso.linux-debian: Eject CD-ROM drives...
==> vsphere-iso.linux-debian: Deleting CD-ROM drives...
==> vsphere-iso.linux-debian: Clear boot order...
==> vsphere-iso.linux-debian: Importing VM OVF template linux-debian-11-v22.11 to Content Library 'm01-lib01' as the item 'linux-debian-11-v22.11' with the description 'Version: v22.11
==> vsphere-iso.linux-debian: Built on: 2022-11-08 03:21 UTC
==> vsphere-iso.linux-debian: Built by: HashiCorp Packer 1.8.4'...
==> vsphere-iso.linux-debian: Destroying VM...
==> vsphere-iso.linux-debian: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-debian' finished after 7 minutes 106 milliseconds.

==> Wait completed after 7 minutes 106 milliseconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
Done.
Press Enter to continue.
```
</details>

<details open>
<summary>Disk-based Source</summary>


```console
CONFIRM: Build a Debian 11 Template for VMware vSphere?

Continue? (y/n)
y
Building a Debian 11 Template for VMware vSphere...
Initializing HashiCorp Packer and required plugins...
Starting the build....
vsphere-iso.linux-debian: output will be in this color.

==> vsphere-iso.linux-debian: Creating CD disk...
    vsphere-iso.linux-debian: xorriso 1.5.4 : RockRidge filesystem manipulator, libburnia project.
    vsphere-iso.linux-debian: Drive current: -outdev 'stdio:/tmp/packer186893249.iso'
    vsphere-iso.linux-debian: Media current: stdio file, overwriteable
    vsphere-iso.linux-debian: Media status : is blank
    vsphere-iso.linux-debian: Media summary: 0 sessions, 0 data blocks, 0 data, 35.9g free
    vsphere-iso.linux-debian: xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
    vsphere-iso.linux-debian: Added to ISO image: directory '/'='/tmp/packer_to_cdrom160613563'
    vsphere-iso.linux-debian: xorriso : UPDATE :       1 files added in 1 seconds
    vsphere-iso.linux-debian: xorriso : UPDATE :       1 files added in 1 seconds
    vsphere-iso.linux-debian: ISO image produced: 188 sectors
    vsphere-iso.linux-debian: Written to medium : 188 sectors at LBA 0
    vsphere-iso.linux-debian: Writing to 'stdio:/tmp/packer186893249.iso' completed successfully.
    vsphere-iso.linux-debian: Done copying paths from CD_dirs
==> vsphere-iso.linux-debian: Uploading packer186893249.iso to packer_cache/packer186893249.iso
==> vsphere-iso.linux-debian: Creating VM...
==> vsphere-iso.linux-debian: Customizing hardware...
==> vsphere-iso.linux-debian: Adding SATA controller...
==> vsphere-iso.linux-debian: Mounting ISO images...
==> vsphere-iso.linux-debian: Adding configuration parameters...
==> vsphere-iso.linux-debian: Set boot order...
==> vsphere-iso.linux-debian: Power on VM...
==> vsphere-iso.linux-debian: Waiting 5s for boot...
==> vsphere-iso.linux-debian: Typing boot command...
==> vsphere-iso.linux-debian: Waiting for IP...
==> vsphere-iso.linux-debian: IP address: 172.16.14.184
==> vsphere-iso.linux-debian: Using SSH communicator to connect: 172.16.14.184
==> vsphere-iso.linux-debian: Waiting for SSH to become available...
==> vsphere-iso.linux-debian: Connected to SSH!
==> vsphere-iso.linux-debian: Provisioning with Ansible...
    vsphere-iso.linux-debian: Setting up proxy adapter for Ansible....
==> vsphere-iso.linux-debian: Executing Ansible: <sensitive>-playbook -e packer_build_name="linux-debian" -e packer_builder_type=vsphere-iso -e packer_http_addr=172.16.11.253:0 --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars display_skipped_hosts=false --extra-vars BUILD_USERNAME=<sensitive> --extra-vars BUILD_SECRET=***** --extra-vars ANSIBLE_USERNAME=<sensitive> --extra-vars ANSIBLE_SECRET=***** -e <sensitive>_ssh_private_key_file=/tmp/<sensitive>-key3190778440 -i /tmp/packer-provisioner-<sensitive>2102458614 /home/packer/packer-vsphere/<sensitive>/main.yml
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY [all] *********************************************************************
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [Gathering Facts] *********************************************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/base/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Updating the guest operating system.] *****************************
    vsphere-iso.linux-debian: ok: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [base : Installing additional packages.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/users/tasks/linux.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys for the default local user.] **************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the default local user to passwordless sudoers.] **********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Creating a local user for Ansible.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding authorized_keys to the local user for Ansible.] ***********
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [users : Adding the local user for Ansible to passwordless sudoers.] ******
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/configure/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Configure SSH for Public Key Authentication.] ****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting hostname to localhost.] ******************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Restarting the SSH daemon.] **********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Disabling and clean tmp.] ************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting SSH keys to regenerate on reboot, if neccessary.] ****
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [configure : Setting guest operating system information.] *****************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian: included: /home/packer/packer-vsphere/<sensitive>/roles/clean/tasks/debian.yml for default
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning all audit logs.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning persistent udev rules.] *********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the /tmp directories] ***********************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the SSH host keys.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the machine-id.] ****************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: TASK [clean : Cleaning the shell history.] *************************************
    vsphere-iso.linux-debian: changed: [default]
    vsphere-iso.linux-debian:
    vsphere-iso.linux-debian: PLAY RECAP *********************************************************************
    vsphere-iso.linux-debian: default                    : ok=24   changed=18   unreachable=0    failed=0    skipped=16   rescued=0    ignored=0
    vsphere-iso.linux-debian:
==> vsphere-iso.linux-debian: Executing shutdown command...
==> vsphere-iso.linux-debian: Deleting Floppy drives...
==> vsphere-iso.linux-debian: Eject CD-ROM drives...
==> vsphere-iso.linux-debian: Deleting CD-ROM drives...
==> vsphere-iso.linux-debian: Clear boot order...
==> vsphere-iso.linux-debian: Importing VM OVF template linux-debian-11-v22.11 to Content Library 'm01-lib01' as the item 'linux-debian-11-v22.11' with the description 'Version: v22.11
==> vsphere-iso.linux-debian: Built on: 2022-11-08 03:29 UTC
==> vsphere-iso.linux-debian: Built by: HashiCorp Packer 1.8.4'...
==> vsphere-iso.linux-debian: Destroying VM...
==> vsphere-iso.linux-debian: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-debian' finished after 7 minutes 19 seconds.

==> Wait completed after 7 minutes 19 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
--> vsphere-iso.linux-debian: linux-debian-11-v22.11
Done.
Press Enter to continue.
```
</details>

**Comment by matteu31400** [comment]
OK, I'm using debian 11 as host.

I'm going to use Ubuntu and test it again.

**Comment by matteu31400** [comment]
I just try it on Ubuntu 22.04 and it's not working.
Where are the log files you need ? I can record where is the issue too if it's easier for you to understand.

**Comment by tenthirtyam** [comment]
Consider recording with [Asciinema](http://asciinema.org) and share any possible changes to the project configuration.

I assume that the `ssh_config` on the host was also updates to allow ssh authentication with RSA keys per the `README.md`?

**Comment by tenthirtyam** [comment]
Please include the same from the Packer host console.

**Comment by tenthirtyam** [comment]
As a test, change the common data source variable from http to disk and run the test once more to see if you get the same result or success. I'd like to rule out environmental.

**Comment by matteu31400** [comment]
If I use disk as data source variable , it's working.
The process is totally different if I use disk.

**Comment by tenthirtyam** [comment]
That's **expected** (_not a bug_), due to the way that one has to work around Debian's installer and mount sr1.

**Comment by tenthirtyam** [comment]
Please provide a similar recording for the failing scenario.

**Comment by matteu31400** [comment]
The video is longer and can't be uploaded here because it's 100Mo. Where can I upload it on english website ? 
I know only french

**Comment by tenthirtyam** [comment]
Need a recording for the failing scenario.

**Comment by matteu31400** [comment]
Done !
https://1drv.ms/v/s!AtpILVXbXteGymed8cy_lv0GelES?e=BehHHM

**Comment by matteu31400** [comment]
If I select auto configure network on the next screen, it's working... 
I don't have any problem with the DHCP in my environment except for this task :/

**Comment by tenthirtyam** [comment]
Unfortunately, I’ve not been able to reproduce this issue.

I’ll take a further look into it in the coming weeks, pending an availability and priorities.

In the meantime, if any watchers or community members are or are not seeing this issue, please use the reactions and comment.

**Comment by tenthirtyam** [comment]
Unfortunately, I’ve still not been able to reproduce this issue. In the meantime, I'll park this in the backlog. 

If any watchers or community members are (_or are not seeing_) this issue, please use the reactions and comment.

If there are no further reports on this question within the next 14 days this issue may be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
